<?php $_product = $block->getProduct(); ?>

<?php
$hideForGuestHelper = $this->helper(\CHK\HideForGuest\Helper\Data::class);
$allowAddToCart = $hideForGuestHelper->getAllowAddtocart();
$customButtonTitle = $hideForGuestHelper->getCustomButtonTitle();
?>

<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable() && ($allowAddToCart || $hideForGuestHelper->isCustomerLoggedIn())) : ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) : ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @noEscape */ __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       value="<?= /* @noEscape */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @noEscape */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= /* @noEscape */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?= /* @noEscape */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    "#product_addtocart_form": {
        "Magento_Catalog/js/validate-product": {}
    }
}
</script>
<?php endif; ?>
<?php if ($customButtonTitle && !$hideForGuestHelper->isCustomerLoggedIn()) { ?>
    <div class="chk_hideforguest_button box-tocart">
        <div class="fieldset">
            <div class="actions">
                <a  class="action tocart primary"
                    href="<?= $block->escapeUrl('customer/account/login'); ?>"
                    title="<?= /* @noEscape */ $customButtonTitle; ?>">
                    <?= /* @noEscape */ $customButtonTitle ?>
                </a>
            </div>
        </div>
    </div>
<?php } ?>
